### ISSUE TITLE
Can someone help me out in delete review. 

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#141]
Udemy Question: https://www.udemy.com/course/mern-ecommerce/learn/lecture/22870685#questions/14725056
I have most of the things done already and I've made constants and all that fun stuff, but when I click the button, it gives me a 401 Unauthorized. If someone can go to my repo and figure that out, I will be so grateful. Thanks!  I just commented out the things in the product screen. Feel free to check the actions and all that.]

Here is my repo:- https://github.com/Obsession-Boutique/Joannie-Store-Shop

**Comment by AstroProjection** [comment]
Hey, could you just screenshot your question and show it to me, I don't have access to that page, i'll help you out

**Comment by talmax1124** [comment]
What do you mean you don't have access to that page @AstroProjection ?

**Comment by talmax1124** [comment]
It is public: https://github.com/Obsession-Boutique/Joannie-Store-Shop/settings

**Comment by AstroProjection** [comment]
https://www.udemy.com/course/mern-ecommerce/learn/lecture/22870685#questions/14725056
I don't have access to your udemy question, because I haven't purchased this course so I'm not exactly sure if there's more to what you've mentioned in your initial post.

Could you just elaborate on exactly when your issue is coming up?

**Comment by talmax1124** [comment]
<img width="1241" alt="Screen Shot 2021-04-28 at 8 47 20 AM" src="https://user-images.githubusercontent.com/61528430/116406176-63a19e00-a7fe-11eb-8b83-e1f500334ce7.png">

Oh, its nothing related to the course. Something I want to implement

**Comment by talmax1124** [comment]
It's the same question

**Comment by talmax1124** [comment]
Are you an experienced mern react developer? I need help in one other thing

**Comment by AstroProjection** [comment]
> It's the same question. Once I click delete, it gives me this unauthorized.
Could you just show me the response you are getting for your 401 error? 
It will be under the 'network' tab in your dev console, just look for the request ending with '/api/product/${productId}/reviews'
And from there just open up the Response tab, and show the 'data' you have in there

> Are you an experienced mern react developer? I need help in one other thing once we finish with this
Yeah sure, I can help you out with it, though I suggest you open up the issue on your repo since it will be easier to track changes there

**Comment by talmax1124** [comment]
Sure, I can do that.
<img width="1171" alt="Screen Shot 2021-04-28 at 9 03 49 AM" src="https://user-images.githubusercontent.com/61528430/116408323-a6fd0c00-a800-11eb-8f90-0fb7f69f8039.png">
<img width="524" alt="Screen Shot 2021-04-28 at 9 03 42 AM" src="https://user-images.githubusercontent.com/61528430/116408362-b1b7a100-a800-11eb-82fb-d43a7543e1aa.png">

**Comment by talmax1124** [comment]
Have you tried cloning the repo?

**Comment by AstroProjection** [comment]
You don't appear to be sending any header 'Authorization' in your request.
It seems to be caused because you've passed the body 'review' where the config should be

`    await axios.delete(`/api/products/${productId}/reviews`, review, config)
`
should be 

`    await axios.delete(`/api/products/${productId}/reviews`, config, review)
`

**Comment by talmax1124** [comment]
Oh, yes because you need to create a .env file with some things

**Comment by talmax1124** [comment]
Ok, so now it's deleting. But it's deleting the product as well

**Comment by AstroProjection** [comment]
> Ok, so now it's deleting. But it's deleting the product as well

Yup, the deletion logic you have in the backend is incorrect.
`
    product.reviews.delete(review);
`
Is not a method.

Just filter the array for the reviews that match the same Id of the review and then save the product instead of removing it

**Comment by talmax1124** [comment]
so should I do it like this?  product.reviews.remove[review];

**Comment by AstroProjection** [comment]
I will create a PR and show you on your repository, though I won't be able to test it, you can do it from your end and merge it into your main branch

**Comment by talmax1124** [comment]
Ok!

**Comment by talmax1124** [comment]
It does nothing: [0] DELETE /api/products/6089626dcc7322a7134fa879/reviews 201 323.964 ms - 28

Once I click, the error does not show, but it does not delete. The thing above is the response from the terminal in VSCODE

@AstroProjection
