### ISSUE TITLE
Setting up the proxy does in package.js does NOT work. It always points to localhost:3000

### ISSUE THREAD

**Issue by jgervin** [bradtraversy/proshop_mern#166]
Package.json
...
"proxy": "http://127.0.0.1:5000",
  "secure": false

So running the app and loading the HomeScreen results in an empty screen with the following log. The Udemy tutorial is worthless with this fix.

xhr.js:177 GET http://localhost:3000/api/poducts 404 (Not Found)

createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

**Comment by basir** [comment]
hello there,
the issue is in backend API. you don't have /api/products in backend API. 
do you have this:
https://github.com/bradtraversy/proshop_mern/blob/master/backend/routes/productRoutes.js#L14
and this:
https://github.com/bradtraversy/proshop_mern/blob/master/backend/controllers/productController.js#L7
Please create issues for errors in this repo here and for errors in your code ask it in Udemy Q/A and mention screenshot of error and source code.
