### ISSUE TITLE
anyone tell the solution

### ISSUE THREAD

**Issue by Nidhi300197** [bradtraversy/proshop_mern#197]
![image](https://user-images.githubusercontent.com/103884807/166116789-25bd6b23-e733-4592-9d1c-3e07a58e7ae7.png)

**Comment by pushkarsingh019** [comment]
Facing the same issue, I am guessing the issue is with how we defined the configuration of dotenv in the seeder.js.

Because the same code is working in the server.js but is giving an error seeder.js

If you have resolved the error, can you share how you did it, if not would love to see your code.

Here's mine: https://github.com/pushkarsingh019/onlineShop

**Comment by behringerdenon** [comment]
that's why there is no environment variables
