### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop. Also Says ListGroupItem is defined but never used.

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#27]
Hello, it is saying there is something wrong with the props. As well as ListGroupItem is defined but it says never used. My repository is in this link. It will stay public for the next 5 days or until I start doing the api with the import stuff. 

./src/screens/ProductScreen.js
  Line 3:51:  'ListGroupItem' is defined but never used  no-unused-vars

and Warning: Each child in a list should have a unique "key" prop.

Check the render method of `HomeScreen`. See https://fb.me/react-warning-keys for more information.
    in Col (at HomeScreen.js:23)
    in HomeScreen (created by Context.Consumer)
    in Route (at App.js:16)
    in div (created by Container)
    in Container (at App.js:15)
    in main (at App.js:14)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:12)
    in App (at src/index.js:10)
    in StrictMode (at src/index.js:9)

https://github.com/talmax1124/cduoshop

**Comment by cdthomp1** [comment]
From looking at your code try taking `ListGroupItem` from your imports as this is not from React Bootstrap, the `ListGroup` component is what you will need. Give that a try and see if that solves your issue.

**Comment by talmax1124** [comment]
> From looking at your code try taking `ListGroupItem` from your imports as this is not from React Bootstrap, the `ListGroup` component is what you will need. Give that a try and see if that solves your issue. 

Do you have an example. I dont think i am understanding you.

**Comment by cdthomp1** [comment]
Sorry if I wasn't clear, your imports from React Bootstrap should look like this `import { Row, Col, Image, ListGroup, Card, Button, Form } from 'react-bootstrap'`. You appear to have `import {Row, Col, Image, ListGroup, Card, Button, ListGroupItem} from 'react-bootstrap'` in your `ProductScreen.js` file. You have `ListGroupItem` defined, but it isn't a component, it is `ListGroup.Item`

As far as the warnings for the home screen, I took a look and found that you are missing the `key` prop on your `<Col>` element. Since we are creating a list inside the `map()` method, we need to add a `key` prop to each item in the list. adding key={product._id}` to the `<Col>` element will solve that error. If you need an example, you can see my file [here](https://github.com/cdthomp1/mern-ecommerce/blob/fb3190d6c0271081f2215733a8b87ab462553abe/frontend/src/screens/HomeScreen.js#L25)

Let me know if you have any other questions or errors.
