### ISSUE TITLE
orderDetailsReducer: the initial state of loading is true?

### ISSUE THREAD

**Issue by tuokaikyle** [bradtraversy/proshop_mern#50]
Maybe it is better to set the initial state of loading to false in orderDetailsReducer, and let ORDER_DETAILS_REQUEST to return only {loading:true}, without the ...state

**Comment by basir** [comment]
in OrderScreen.js in the return statement, we check `loading` and it should be true while the component mount, otherwise user will see invalid data or error. that is why we set it to true. if you set it to true in the initial state there is no need to set `, orderItems: [], shippingAddress: {}` for initial state.
also there is no need to have ...sate to keep other data of the state by this design.
