### ISSUE TITLE
product Image dissappers after some time

### ISSUE THREAD

**Issue by Derry-ukere** [bradtraversy/proshop_mern#52]
i dnt why but when i upload an image in the create product, after some time i dont see the image again

**Comment by basir** [comment]
please only issue bugs of this repo here. ask questions in the Udemy Q/A.
About this issue, I can not find this error. when you upload a file in /uploads folder it remains there and will be served forever. 
if you have this issue on Heroku it is normal because Heroku reset the server after 30mins idle.
